### ISSUE TITLE
Make blindsight available on maven central

### ISSUE THREAD

**Issue by francisdb** [tersesystems/blindsight#163]
We are not allowed to use repositories that might go away one day

Maven central sync is not that hard to set up
https://www.jfrog.com/confluence/display/BT/Syncing+with+Third-Party+Platforms

**Comment by wsargent** [comment]
Resolved as of 1.4.1 

https://mvnrepository.com/artifact/com.tersesystems.blindsight/blindsight-api_2.13/1.4.1
