### ISSUE TITLE
doc clarification re: blindsight.source.enabled

### ISSUE THREAD

**Issue by dpennell** [tersesystems/blindsight#179]
You need to use `<property name="blindsight.source.enabled" value="true" scope="context"/>` instead of `<property name="blindsight.source.enabled" value="true"/>`

Without `scope="context"`, the property is not saved in the logger context's propertyMap.

See https://stackoverflow.com/questions/14271253/access-properties-defined-in-logback-programmatically

**Comment by wsargent** [comment]
D'oh, yes.  It doesn't save it in that scope automatically.

**Comment by dpennell** [comment]
I noticed a `context` section in the conf file that claims to be a way to populate properties into that scope.  I haven't tried it, but I wonder if that should be preferred over adding xml.
