### ISSUE TITLE
Logger eagerly evaluates the message before checking the log level

### ISSUE THREAD

**Issue by kamilkloch** [tersesystems/blindsight#475]
With log level set to `INFO`, the following snippet 
```scala
logger.debug({ println("this should not be printed"); ""})
```
prints
```
this should not be printed
```

This is arguably an undesired behavior. Compare with https://github.com/lightbend-labs/scala-logging, where you can call log methods, without checking whether the respective log level is enabled.

**Comment by wsargent** [comment]
The first argument is an argument template, which takes a static string -- if you want to render an argument as the only thing in the template, you would typically do it using `logger.debug("{}", Arguments("foo"))`.

You can use [lazy blocks](https://tersesystems.github.io/blindsight/usage/slf4j.html#lazy-blocks) for preference:

```
logger.debug { debug =>
  val debugInfo = ...
  debug(st"I am a debugging statement with lots of extra $debugInfo")
}
```
