### ISSUE TITLE
`log.isXXXEnabled()` causes allocation overhead

### ISSUE THREAD

**Issue by kamilkloch** [tersesystems/blindsight#476]
`log.isDebugEnabled()` causes a lot of unnecessary allocations, going through 

```scala
    override def predicate(level: Level): CorePredicate =
      new CorePredicate.Impl(level, this)
```

in `CoreLogger.Abstract`

Arguably, this operation should be as lightweight as possible.

**Comment by wsargent** [comment]
It's assigned to a val.

https://github.com/tersesystems/blindsight/blob/8bd69d5a164420dece13809049d10f4401453dad/api/src/main/scala/com/tersesystems/blindsight/slf4j/SLF4JLogger.scala#L53

Please see https://tersesystems.github.io/blindsight/performance/memory.html and https://tersesystems.github.io/blindsight/performance/benchmarks.html and I also wrote a couple of blog posts:

* https://tersesystems.com/blog/2020/07/09/logging-vs-memory/
* https://tersesystems.com/blog/2020/08/23/benchmarking-logging-with-jdk-14/
